version: 2
jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: python -m venv env
      - run:
          name: Build Docker Image and Push to ECR
          command: |
            COMMIT_ID=$(echo $CIRCLE_SHA1 | cut -c1-7)
            . env/bin/activate
            pip install -U awscli awsebcli ebi
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws ecr get-login --no-include-email --region ap-northeast-1 | /bin/bash
            cd ~/myapp
            cd rundeck3
            docker build -t rundeck3docker .
            docker tag  rundeck3docker:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/rundeck3docker:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/rundeck3docker:latest
            cd ~/myapp
            cd oauth2_proxy
            docker build -t oauth2_proxy_docker .
            docker tag  oauth2_proxy_docker:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/oauth2_proxy_docker:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/oauth2_proxy_docker:latest
            cd ~/myapp
            cd nginx_4_oauth2_proxy
            docker build -t nginx_4_oauth2_proxy .
            docker tag  nginx_4_oauth2_proxy:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_4_oauth2_proxy:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_4_oauth2_proxy:latest
  test-tf:
    working_directory: ~/ecs
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: copy env for terraform
          command: |
            export  TF_VAR_access_key=$AWS_ACCESS_KEY_ID
            export  TF_VAR_secret_key=$AWS_SECRET_ACCESS_KEY
            export -p
            cd ~/ecs
      - run:
          name: Init terraform
          command: terraform init ~/ecs
      - run:
          name: Validate terraform
          command: terraform validate ~/ecs
      - run:
          name: Plan terraform
          command: terraform plan ~/ecs
  deploy-tf:
    working_directory: ~/ecs
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: copy env for terraform
          command: |
            export  TF_VAR_access_key=$AWS_ACCESS_KEY_ID
            export  TF_VAR_secret_key=$AWS_SECRET_ACCESS_KEY
            export -p
            cd ~/ecs      
      - run:
          name: Init terraform
          command: terraform init ~/ecs
      - run:
          name: Apply terraform
          command: terraform apply -auto-approve ~/ecs


workflows:
  version: 2
  fuga:
    jobs:
      - build
      - test-tf
      - deploy-tf